In [1]:
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
owid_data = pd.read_csv("../data/owid/owid-energy-data.csv")
owid_data

,iso_code,country,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,...,solar_elec_per_capita,solar_energy_per_capita,gdp,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
0,AFG,Afghanistan,1900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,1901,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Afghanistan,1902,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Afghanistan,1903,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Afghanistan,1904,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17427,ZWE,Zimbabwe,2015,-25.013,-10.847,NaN,NaN,NaN,NaN,-0.789,...,0.579,NaN,2.503057e+10,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17428,ZWE,Zimbabwe,2016,-37.694,-12.257,NaN,NaN,NaN,NaN,-14.633,...,0.641,NaN,2.515176e+10,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17429,ZWE,Zimbabwe,2017,8.375,1.697,NaN,NaN,NaN,NaN,NaN,...,0.773,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17430,ZWE,Zimbabwe,2018,22.555,4.952,NaN,NaN,NaN,NaN,NaN,...,0.970,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17431,ZWE,Zimbabwe,2019,-35.015,-9.422,NaN,NaN,NaN,NaN,NaN,...,0.956,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN

In [14]:
countries_in_europe = pd.read_csv("../data/misc/countries_in_europe.csv").drop(columns=["zoom", "abbreviation", "continent"])
countries_in_europe

,name,ISO alpha 2,ISO alpha 3,ISO numeric,land area km,population,latitude,longitude
0,Ukraine,UA,UKR,804,603700.0,45415596,49.00,32.00
1,France,FR,FRA,250,547030.0,64768389,46.00,2.00
2,Spain,ES,ESP,724,504782.0,46505963,40.00,-4.00
3,Sweden,SE,SWE,752,449964.0,9045000,62.00,15.00
4,Germany,DE,DEU,276,357021.0,82369000,51.50,10.50
5,Finland,FI,FIN,246,337030.0,5244000,64.00,26.00
6,Norway,NO,NOR,578,324220.0,4907000,62.00,10.00
7,Poland,PL,POL,616,312685.0,38500000,52.00,20.00
8,Italy,IT,ITA,380,301230.0,58145000,42.83,12.83
9,United Kingdom,GB,GBR,826,244820.0,62348447,54.90,-3.12
10,Romania,RO,ROU,642,237500.0,21959278,46.00,25.00
11,Belarus,BY,BLR,112,207600.0,9685000,53.00,28.00
12,Greece,GR,GRC,300,131940.0,11000000,39.00,22.00
13,Bulgaria,BG,BGR,100,110910.0,7148785,43.00,25.00
14,Iceland,IS,ISL,352,103000.0,308910,65.00,-18.00
15,Portugal,PT,PRT,620,92391.0,10676000,39.50,-8.00
16,Czech Republic,CZ,CZE,203,78866.0,10476000,49.75,15.00
17,Denmark,DK,DNK,208,43094.0,5484000,56.00,10.00
18,Hungary,HU,HUN,348,93030.0,9930000,47.00,20.00
19,Serbia,RS,SRB,688,88361.0,7344847,44.82,20.46
20,Austria,AT,AUT,40,83858.0,8205000,47.33,13.33
21,Ireland,IE,IRL,372,70280.0,4622917,53.00,-8.00
22,Lithuania,LT,LTU,440,65200.0,3565000,56.00,24.00
23,Latvia,LV,LVA,428,64589.0,2217969,57.00,25.00
24,Croatia,HR,HRV,191,56542.0,4491000,45.17,15.50
25,Bosnia and Herzegovina,BA,BIH,70,51129.0,4590000,44.25,17.83
26,Slovakia,SK,SVK,703,48845.0,5455000,48.67,19.50
27,Estonia,EE,EST,233,45226.0,1291170,59.00,26.00
28,Netherlands,NL,NLD,528,41526.0,16645000,52.50,5.75
29,Switzerland,CH,CHE,756,41290.0,7581000,47.00,8.01
30,Moldova,MD,MDA,498,33843.0,4324000,47.00,29.00
31,Belgium,BE,BEL,56,30510.0,10403000,50.83,4.00
32,Albania,AL,ALB,8,28748.0,2986952,41.00,20.00
33,Macedonia,MK,MKD,807,25333.0,2061000,41.83,22.00
34,Slovenia,SI,SVN,705,20273.0,2007000,46.25,15.17
35,Montenegro,ME,MNE,499,14026.0,666730,43.50,19.30
36,Cyprus,CY,CYP,196,9250.0,1102677,35.00,33.00
37,Luxembourg,LU,LUX,442,2586.0,497538,49.75,6.17
38,Faroe Is.,FO,FRO,234,1399.0,48228,62.00,-7.00
39,Andorra,AD,AND,20,468.0,84000,42.50,1.50
40,Malta,MT,MLT,470,316.0,403000,35.92,14.43
41,Liechtenstein,LI,LIE,438,160.0,35000,47.17,9.53
42,Guernsey,GG,GGY,831,78.0,65228,49.58,-2.33
43,San Marino,SM,SMR,674,61.2,31477,43.93,12.42
44,Gibraltar,GI,GIB,292,6.5,27884,36.13,-5.35
45,Monaco,MC,MCO,492,2.0,32965,43.73,7.42
46,Vatican City,VA,VAT,336,0.4,921,41.90,12.45

In [23]:
owid_data[owid_data["iso_code"].isin(countries_in_europe["ISO alpha 3"])]

,iso_code,country,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,...,solar_elec_per_capita,solar_energy_per_capita,gdp,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
240,ALB,Albania,1900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,8.088000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
241,ALB,Albania,1901,NaN,0.000,NaN,0.000,NaN,0.000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242,ALB,Albania,1902,NaN,0.000,NaN,0.000,NaN,0.000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243,ALB,Albania,1903,NaN,0.000,NaN,0.000,NaN,0.000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,ALB,Albania,1904,NaN,0.000,NaN,0.000,NaN,0.000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16244,GBR,United Kingdom,2016,-51.098,-31.996,2.649,10.770,4.763,25.043,-1.191,...,156.987,394.790,2.580000e+12,11.097,-8.292,4.197,-8.448,93.437,560.423,1409.350
16245,GBR,United Kingdom,2017,-25.755,-7.887,0.351,1.465,-1.716,-9.454,-0.283,...,171.976,429.941,NaN,14.894,32.798,5.590,30.646,124.083,743.823,1859.558
16246,GBR,United Kingdom,2018,-15.312,-3.481,-3.260,-13.656,9.093,49.232,-0.337,...,191.495,475.938,NaN,17.336,13.979,6.393,17.345,141.428,847.517,2106.403
16247,GBR,United Kingdom,2019,-16.060,-3.092,-2.196,-8.897,1.811,10.695,-1.560,...,192.062,464.830,NaN,20.195,12.291,7.292,17.382,158.810,955.536,2351.701
16248,GBR,United Kingdom,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,196.709,NaN,NaN,24.151,NaN,NaN,NaN,NaN,1086.757,NaN